import './catalog-detail-gallery'
import './catalog-detail-gallery-modal'
import './catalog-detail-price-and-color'
import './catalog-detail-sizes-btns'
import './catalog-detail-info'
import './catalog-detail-table-size'
