import './catalog-detail.init'
import './catalog-detail.scss'
import './catalog-detail-info.sass'
import './catalog-detail-price-and-color.sass'
import './catalog-detail-table-size.sass'
import './catalog-detail-gallery'
import './catalog-detail-gallery-modal'
import './catalog-detail-sizes-btns'
