import './catalog-detail.init'
import './catalog-detail.scss'
import './elements'
import './catalog-detail-info.sass'
import './catalog-detail-price-and-color.sass'
import './catalog-detail-table-size.sass'
